### ISSUE TITLE
vimeo advanced options

### ISSUE THREAD

**Issue by telemarker** [findingsimple/acf-field-video#10]
hi, is there a way to include some advanced embed options in vimeo.
e.g. hide the title, ...

regards
thomas

**Comment by jconroy** [comment]
No not at the moment. This was designed to be a very simple plugin for a specific use case.

If I have time sometime I'll look it but its definitely not on my to-do list.

**Comment by telemarker** [comment]
okay i found another solution using html 5 <video> tag and deinstalled the plugin.
