### ISSUE TITLE
ACF5 Compatibility

### ISSUE THREAD

**Issue by leocaseiro** [findingsimple/acf-field-video#4]
It's not working on ACF5. If I have time I'll fix, but for a while I'm using oEmbed instead of.

**Comment by sebastienserre** [comment]
Hello leocaseiro, how to use your fix?

many thx

**Comment by leocaseiro** [comment]
You might want to try to use my version https://github.com/leocaseiro/acf-field-video instead.

My PR #5 hasn't been approved yet...

**Comment by sebastienserre** [comment]
Thx for your reply. It's what I've done later after posting here.
Why don't you submit it to official WordPress Repo?

**Comment by leocaseiro** [comment]
I was hopping someone from @jconroy would accept my PR.

**Comment by leocaseiro** [comment]
The fix has been merged
