### ISSUE TITLE
video responsive size

### ISSUE THREAD

**Issue by telemarker** [findingsimple/acf-field-video#8]
hi, i implemented videos with your plugin.
it works but the how can i change the size of the videos to 100% width and auto height?
check out: http://framegrabber.firstkat.de/portfolios/slideshowtest/

the videos are always 500px in width. i like them to use always 100% of the slideshow size (so it also works in responsive mode).
thanks and many regards
thomas

**Comment by jconroy** [comment]
Hi Thomas,

How you display on the front end is up to you / your developer. 

This plugin is for adding a field to the dashboard. Nothing more - and was built for a specific use case.

You could use something like http://fitvidsjs.com/ to make your videos responsive. This is what we use in the dashboard.

**Comment by telemarker** [comment]
okay i found another solution using html 5 <video> tag and deinstalled the plugin.
