### ISSUE TITLE
use the video field for embed AND thumbnail

### ISSUE THREAD

**Issue by telemarker** [findingsimple/acf-field-video#9]
hi, i am using a carousel flexslider slideshow (thumbnail slider works as a navigation).

is there the posibilty to use one acf-video field for the 2 elements (embed and thumbnail)?
this would increase the user experience. right now i use 2 fields, one for embed-output and one for thumbnail-output. i am sure there is a more simple way to do it.

thanks
thomas

**Comment by jconroy** [comment]
Hi, I don't think so at the moment. Whenever I get a chance to look at the plugin again I'll have a play. Otherwise feel free to modify and submit a pull request. Thanks for the idea.

**Comment by telemarker** [comment]
okay i found another solution using html 5 <video> tag and deinstalled the plugin.
